DROP TABLE CCCUSTID;

CREATE TABLE `CCCUSTID` (
  `CUST_SEQ` int(10) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1
;

/*
-- Query: select * from CCCUSTID
LIMIT 0, 50000

-- Date: 2018-06-25 01:35
*/
INSERT INTO `CCCUSTID` (`CUST_SEQ`) VALUES (456);
